### ISSUE TITLE
Bug: Open trap doors from underneath

### ISSUE THREAD

**Issue by Gorn14** [smokin-guns/SmokinGuns#1]
When i open a trap and i am on a ladder.
The door open, close, open, close, open, ... (lag)

Testing :
- Santa Fe Express (the car with the trunk of gold)
- Mine (the house with fireplace)
- Hang'em high (prison-like room, next to library)

More information :
Gorn - http://forum.smokin-guns.org/viewtopic.php?f=33&t=2361
TheDoctor - http://forum.smokin-guns.org/viewtopic.php?f=22&t=2445 (+ patch !!!)

**Comment by smokin-guns** [comment]
Thank you again for the report.
The case is fixed now in 43e8946d7a8ad49caa9467c98dd97a22be561a00 commit.
