### ISSUE TITLE
Bug: Game mode in menu

### ISSUE THREAD

**Issue by Gorn14** [smokin-guns/SmokinGuns#2]
Bug with "Team Deathmatch" for exemple :

1 - Launch smokin guns > Start Server > Select "Team Deathmatch"
2 - Exit
3 - Launch smokin guns > Start Server (there are one team with "Team Deathmatch" game mode)

Screenshot here: http://forum.smokin-guns.org/viewtopic.php?f=33&t=2360

**Comment by smokin-guns** [comment]
Thanks to vloup this is fix in 9d7afe2b92efffb51a828f845b262476c3df142f
