### ISSUE TITLE
"Score Limit" in HUD

### ISSUE THREAD

**Issue by Gorn14** [smokin-guns/SmokinGuns#3]
Score Limit in HUD = 99
Up to 999 or more
Please see : http://forum.smokin-guns.org/viewtopic.php?f=33&t=2358

**Comment by smokin-guns** [comment]
We will support only score up to 999 in HUD in a lower size font. Greater score needs a full HUD redesign.
Fixed in 036053b6077588e0bbccf63525cac44cfb4f1c8e
